package DiffusersSynopsis.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;
import jetbrains.mps.smodel.runtime.base.BasePropertyConstraintsDescriptor;
import jetbrains.mps.smodel.runtime.ConstraintsDescriptor;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.smodel.runtime.CheckingNodeContext;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.smodel.SNodePointer;
import java.util.Map;
import org.jetbrains.mps.openapi.language.SProperty;
import jetbrains.mps.smodel.runtime.PropertyConstraintsDescriptor;
import java.util.HashMap;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class Synopsis_Constraints extends BaseConstraintsDescriptor {
  public Synopsis_Constraints() {
    super(CONCEPTS.Synopsis$nM);
  }

  public static class CFG_scale_Property extends BasePropertyConstraintsDescriptor {
    public CFG_scale_Property(ConstraintsDescriptor container) {
      super(PROPS.CFG_scale$2OV7, container, false, false, true);
    }
    @Override
    public boolean validateValue(SNode node, Object propertyValue, CheckingNodeContext checkingNodeContext) {
      boolean result = staticValidateProperty(node, SPropertyOperations.castString(propertyValue));
      if (!(result) && checkingNodeContext != null) {
        checkingNodeContext.setBreakingNode(new SNodePointer("r:e8463b0f-9463-42a9-a3cb-ceffad1499be(DiffusersSynopsis.constraints)", "5030534239781345710"));
      }
      return result;
    }
    private static boolean staticValidateProperty(SNode node, String propertyValue) {
      if (propertyValue != null) {
        return Float.parseFloat(propertyValue) >= 0.0;
      }
      return true;
    }
  }
  public static class Width_Property extends BasePropertyConstraintsDescriptor {
    public Width_Property(ConstraintsDescriptor container) {
      super(PROPS.width$x1Oh, container, false, false, true);
    }
    @Override
    public boolean validateValue(SNode node, Object propertyValue, CheckingNodeContext checkingNodeContext) {
      boolean result = staticValidateProperty(node, SPropertyOperations.castInteger(propertyValue));
      if (!(result) && checkingNodeContext != null) {
        checkingNodeContext.setBreakingNode(new SNodePointer("r:e8463b0f-9463-42a9-a3cb-ceffad1499be(DiffusersSynopsis.constraints)", "5030534239781356273"));
      }
      return result;
    }
    private static boolean staticValidateProperty(SNode node, int propertyValue) {
      return propertyValue >= 1;
    }
  }
  public static class Height_Property extends BasePropertyConstraintsDescriptor {
    public Height_Property(ConstraintsDescriptor container) {
      super(PROPS.height$meRg, container, false, false, true);
    }
    @Override
    public boolean validateValue(SNode node, Object propertyValue, CheckingNodeContext checkingNodeContext) {
      boolean result = staticValidateProperty(node, SPropertyOperations.castInteger(propertyValue));
      if (!(result) && checkingNodeContext != null) {
        checkingNodeContext.setBreakingNode(new SNodePointer("r:e8463b0f-9463-42a9-a3cb-ceffad1499be(DiffusersSynopsis.constraints)", "5030534239781363190"));
      }
      return result;
    }
    private static boolean staticValidateProperty(SNode node, int propertyValue) {
      return propertyValue >= 1;
    }
  }
  public static class Steps_Property extends BasePropertyConstraintsDescriptor {
    public Steps_Property(ConstraintsDescriptor container) {
      super(PROPS.steps$er3Y, container, false, false, true);
    }
    @Override
    public boolean validateValue(SNode node, Object propertyValue, CheckingNodeContext checkingNodeContext) {
      boolean result = staticValidateProperty(node, SPropertyOperations.castInteger(propertyValue));
      if (!(result) && checkingNodeContext != null) {
        checkingNodeContext.setBreakingNode(new SNodePointer("r:e8463b0f-9463-42a9-a3cb-ceffad1499be(DiffusersSynopsis.constraints)", "5030534239781370886"));
      }
      return result;
    }
    private static boolean staticValidateProperty(SNode node, int propertyValue) {
      return propertyValue >= 1;
    }
  }
  @Override
  protected Map<SProperty, PropertyConstraintsDescriptor> getSpecifiedProperties() {
    Map<SProperty, PropertyConstraintsDescriptor> properties = new HashMap<SProperty, PropertyConstraintsDescriptor>();
    properties.put(PROPS.CFG_scale$2OV7, new CFG_scale_Property(this));
    properties.put(PROPS.width$x1Oh, new Width_Property(this));
    properties.put(PROPS.height$meRg, new Height_Property(this));
    properties.put(PROPS.steps$er3Y, new Steps_Property(this));
    return properties;
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept Synopsis$nM = MetaAdapterFactory.getConcept(0x6d5fbab605684ec4L, 0xbb6a34c38dc971e3L, 0x45d00c3cf897b179L, "DiffusersSynopsis.structure.Synopsis");
  }

  private static final class PROPS {
    /*package*/ static final SProperty CFG_scale$2OV7 = MetaAdapterFactory.getProperty(0x6d5fbab605684ec4L, 0xbb6a34c38dc971e3L, 0x45d00c3cf897b179L, 0x45d00c3cf8995c7fL, "CFG_scale");
    /*package*/ static final SProperty width$x1Oh = MetaAdapterFactory.getProperty(0x6d5fbab605684ec4L, 0xbb6a34c38dc971e3L, 0x45d00c3cf897b179L, 0x45d00c3cf89970b0L, "width");
    /*package*/ static final SProperty height$meRg = MetaAdapterFactory.getProperty(0x6d5fbab605684ec4L, 0xbb6a34c38dc971e3L, 0x45d00c3cf897b179L, 0x45d00c3cf8996f70L, "height");
    /*package*/ static final SProperty steps$er3Y = MetaAdapterFactory.getProperty(0x6d5fbab605684ec4L, 0xbb6a34c38dc971e3L, 0x45d00c3cf897b179L, 0x45d00c3cf89957bcL, "steps");
  }
}
