package DiffusersSynopsis.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_Sampler extends EnumerationDescriptorBase {

  public EnumerationDescriptor_Sampler() {
    super(0x6d5fbab605684ec4L, 0xbb6a34c38dc971e3L, 0x45d00c3cf8995b06L, "Sampler", "r:c7c563d7-3ff3-4511-b4ec-8885143ec458(DiffusersSynopsis.structure)/5030534239781214982");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_EulerA_0 = new EnumerationDescriptor.MemberDescriptor("EulerA", "Euler a", 0x45d00c3cf8995b07L, "r:c7c563d7-3ff3-4511-b4ec-8885143ec458(DiffusersSynopsis.structure)/5030534239781214983");
  private final EnumerationDescriptor.MemberDescriptor myMember_Heun_0 = new EnumerationDescriptor.MemberDescriptor("Heun", "Heun", 0x45d00c3cf8995bb1L, "r:c7c563d7-3ff3-4511-b4ec-8885143ec458(DiffusersSynopsis.structure)/5030534239781215153");
  private final EnumerationDescriptor.MemberDescriptor myMember_DDIM_0 = new EnumerationDescriptor.MemberDescriptor("DDIM", "DDIM", 0x45d00c3cf8995bb4L, "r:c7c563d7-3ff3-4511-b4ec-8885143ec458(DiffusersSynopsis.structure)/5030534239781215156");
  private final EnumerationDescriptor.MemberDescriptor myMember_DPMpp2M_0 = new EnumerationDescriptor.MemberDescriptor("DPMpp2M", "DPM++ 2M", 0x45d00c3cf8995bb9L, "r:c7c563d7-3ff3-4511-b4ec-8885143ec458(DiffusersSynopsis.structure)/5030534239781215161");
  private final EnumerationDescriptor.MemberDescriptor myMember_DPMpp2SaKarras_0 = new EnumerationDescriptor.MemberDescriptor("DPMpp2SaKarras", "DPM++ 2S a Karras", 0x45d00c3cf8995bc0L, "r:c7c563d7-3ff3-4511-b4ec-8885143ec458(DiffusersSynopsis.structure)/5030534239781215168");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0x6d5fbab605684ec4L, 0xbb6a34c38dc971e3L, 0x45d00c3cf8995b06L, 0x45d00c3cf8995b07L, 0x45d00c3cf8995bb1L, 0x45d00c3cf8995bb4L, 0x45d00c3cf8995bb9L, 0x45d00c3cf8995bc0L);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_EulerA_0, myMember_Heun_0, myMember_DDIM_0, myMember_DPMpp2M_0, myMember_DPMpp2SaKarras_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return null;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "EulerA":
        return myMember_EulerA_0;
      case "Heun":
        return myMember_Heun_0;
      case "DDIM":
        return myMember_DDIM_0;
      case "DPMpp2M":
        return myMember_DPMpp2M_0;
      case "DPMpp2SaKarras":
        return myMember_DPMpp2SaKarras_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
