package txtPersistence.txtPersistence;

/*Generated by MPS */

import jetbrains.mps.smodel.EditableModelDescriptor;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.mps.openapi.model.SModelReference;
import org.jetbrains.mps.openapi.persistence.DataSource;
import jetbrains.mps.smodel.ModelLoadResult;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.DefaultSModel;
import jetbrains.mps.smodel.persistence.def.ModelReadException;
import org.jetbrains.mps.openapi.persistence.ModelLoadException;
import jetbrains.mps.smodel.loading.ModelLoadingState;
import java.util.Collection;
import org.jetbrains.mps.openapi.language.SLanguage;
import java.util.Collections;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.annotations.ApiStatus;

public class DiffusersSynopsisModelDescriptor extends EditableModelDescriptor {
  public DiffusersSynopsisModelDescriptor(@NotNull SModelReference modelReference, @NotNull DataSource dataSource) {
    super(modelReference, dataSource);
  }

  @NotNull
  @Override
  protected ModelLoadResult<SModel> createModel() {
    return new ModelLoadResult<>(new DefaultSModel.InvalidDefaultSModel(this.getReference(), new ModelReadException("Did not implemented loading", new ModelLoadException("not implemented"))), ModelLoadingState.NOT_LOADED);
  }

  @Override
  public Collection<SLanguage> importedLanguageIds() {
    return Collections.singleton(MetaAdapterFactory.getLanguage(0x6d5fbab605684ec4L, 0xbb6a34c38dc971e3L, "DiffusersSynopsis"));
  }

  @Override
  public void rename(@NotNull String string, boolean b) {
  }

  @Deprecated
  @ApiStatus.ScheduledForRemoval(inVersion = "2021.2")
  @Override
  public void updateTimestamp() {
  }

  @Override
  public boolean needsReloading() {
    return false;
  }

  @Override
  public void reloadFromSource() {
  }
}
